#!/usr/bin/env bash
# Configures a brand new Ubuntu machine to include a custom Nginx response header

# Update and install Nginx
sudo apt-get -y update
sudo apt-get -y install nginx

# Define the Nginx configuration file
config="/etc/nginx/sites-available/default"

# Add custom header with the hostname of the server
# Using the $HOSTNAME variable which should contain the system's hostname
sudo sed -i "0,/server_name _;/a \\\tadd_header X-Served-By $HOSTNAME;" $config

# Restart Nginx to apply the changes
sudo service nginx restart